Repository munterfi/hereR, pull requests merged in 2020-12, with the labels that each got.

#92 Clarify connection documentation
  R/connection.R
  man/connection.Rd
Labels: documentation

#95 Feature/update isoline api
  DESCRIPTION
  NEWS.md
  R/checks.R
  R/connection.R
  R/geocode.R
  R/intermodal_route.R
  R/isoline.R
  R/sysdata.rda
  R/utils.R
  README.md
  man/geocode.Rd
  man/isoline.Rd
  tests/testthat/test-isoline.R
  vignettes/geocoder.Rmd
  vignettes/routing.Rmd
  vignettes/transit.Rmd
Labels: bug, enhancement

#97 Feature/update routing api
  NEWS.md
  R/checks.R
  R/intermodal_route.R
  R/isoline.R
  R/route.R
  R/sysdata.rda
  README.md
  man/isoline.Rd
  man/route.Rd
  tests/testthat/test-route.R
  vignettes/routing.Rmd
Labels: enhancement

#99 Feature/update matrix routing api
  NEWS.md
  R/autosuggest.R
  R/checks.R
  R/geocode.R
  R/isoline.R
  R/reverse_geocode.R
  R/route_matrix.R
  R/sysdata.rda
  R/utils.R
  man/autosuggest.Rd
  man/geocode.Rd
  man/isoline.Rd
  man/reverse_geocode.Rd
  man/route_matrix.Rd
  tests/testthat/test-route_matrix.R
  vignettes/routing.Rmd
Labels: enhancement

#100 Add issue template, CODE_OF_CONDUCT.md and move to .github folder.
  .Rbuildignore
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
Labels: enhancement

#103 Bugfix/geocode error
  NEWS.md
  R/geocode.R
  R/route_matrix.R
  R/sysdata.rda
  R/utils.R
  R/weather.R
Labels: bug
