Repository munterfi/hereR, pull requests merged in 2020-11, with the labels that each got.

#80 document geocode positions
  R/geocode.R
  man/geocode.Rd
Labels: documentation

#84 Alternative location in geocode
  DESCRIPTION
  NEWS.md
  R/geocode.R
  man/geocode.Rd
  tests/testthat/test-geocode.R
Labels: enhancement

#86 Bugfix/timezone offset
  NEWS.md
  R/sysdata.rda
  R/utils.R
Labels: bug

#88 Release/0.5.2
  DESCRIPTION
  NEWS.md
  R/geocode.R
  R/sysdata.rda
  R/utils.R
  man/geocode.Rd
  tests/testthat/test-geocode.R
Labels: release

#90 Correct wrong parameter name in isoline.
  README.md
Labels: bug, documentation
